all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /home/admin/ansible-venv/devops-livecoding/id_rsa
    ansible_become: true
    ansible_become_method: sudo
  children:
    prod:
      hosts:
        mouhamadou.gueye.takima.cloud
