name: CI devops 2024

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Check out the source code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Step 2: Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Step 3: Build and test with Maven
      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml

      # Step 3.5: Debug file structure
      - name: Debug file structure
        run: ls -R ./simple-api

      # Step 4: Build, test, and analyze with SonarCloud
      - name: Build, test, and analyze with SonarCloud
        run: |
          cd simple-api
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=acbbiste17_devops-livecoding \
            -Dsonar.organization=acbbiste17 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
